name: "This is my blog!"

author:
    name: 'Felipe Arag&atilde;o'
    bio: I'm a 18-year-old living in Rio de Janeiro. I program some stuff.
    twitter: f03lipe

description: You don't want to read it.
meta_description: "This is my blog."

markdown: redcarpet
pygments: true
logo: false
paginate: 5
permalink: pretty

pygments: true
exclude: [unicorn.rb, README.md, Procfile, Gemfile, Gemfile.lock, config.ru, vendor, Rakefile, .gitignore]